version: '3.4'

services:

  # REF: https://hub.docker.com/r/arm32v7/telegraf
  telegraf:
    image: arm32v7/telegraf:1.10.0
    hostname: telegraf
      environment:
        - HOST_PROC=/host/proc
        - INFLUX_URL="http://influxdb:8086"
    ports:
      # Telegraf unencrypted UDP 8092
      - mode: host
        target: 8092
        published: 8092
        protocol: udp
      # Telegraf unencrypted TCP 8094
      - mode: host
        target: 8094
        published: 8094
        protocol: tcp
      # Telegraf StatsD unencrypted TCP 8125
      - mode: host
        target: 8125
        published: 8125
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/telegraf/etc/telegraf
        target: /etc/telegraf
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      labels:
        local.description: "Telegraf"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm32v7/influxdb
  influxdb:
    image: arm32v7/influxdb:1.7.4
    hostname: influxdb
      environment:
        - INFLUXDB_GRAPHITE_ENABLED=true
    ports:
      # InfluxDB Graphite unencrypted TCP 2003
      - mode: host
        target: 2003
        published: 2003
        protocol: tcp
      # InfluxDB HTTP API unencrypted TCP 8086
      - mode: host
        target: 8086
        published: 8086
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/influxdb/etc/influxdb
        target: /etc/influxdb
      - type: bind
        source: /opt/influxdb/var/lib/influxdb
        target: /var/lib/influxdb
    deploy:
      labels:
        local.description: "InfluxDB"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm32v7/chronograf
  chronograf:
    image: arm32v7/chronograf:1.7.8
    hostname: chronograf
      environment:
        - influxdb-url=http://influxdb:8086
    ports:
      # Chronograf unencrypted TCP 8888
      - mode: host
        target: 8888
        published: 8888
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/chronograf/var/lib/chronograf
        target: /var/lib/chronograf
    deploy:
      labels:
        local.description: "Chronograf"
      restart_policy:
        condition: on-failure

  # REF: https://hub.docker.com/r/arm32v7/kapacitor
  kapacitor:
    image: arm32v7/kapacitor:1.5.2
    hostname: kapacitor
    ports:
      # Kapacitor unencrypted TCP 9092
      - mode: host
        target: 9092
        published: 9092
        protocol: tcp
    networks:
      - tick-stack-net1
    volumes:
      - type: bind
        source: /opt/kapacitor/var/lib/kapacitor
        target: /var/lib/kapacitor
    deploy:
      labels:
        local.description: "Kapacitor"
      restart_policy:
        condition: on-failure

networks:
  tick-stack-net1:
